# Generated by Django 4.2.2 on 2023-06-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice', models.FileField(upload_to='D:\\code\\biometry\\web_biometry\\samples\\%y-%m-%d')),
            ],
        ),
    ]
